### ISSUE TITLE
Post使用时出现跨域的问题

### ISSUE THREAD

**Issue by Drew233** [cachecleanerjeet/CloudflareDB#2]
你好，我在通过javascript中的XMLHttpRequest使用的时候发现GET可以正常使用，但是POST会出现跨域的问题

问题代码
```
<script>
    var data = new FormData();
    data.append("username", "test");

    var xhr = new XMLHttpRequest();
    xhr.withCredentials = true;

    xhr.addEventListener("readystatechange", function() {
    if(this.readyState === 4) {
        console.log(this.responseText);
    }
    });

    xhr.open("POST", "https://test.miaodrew.workers.dev/");

    xhr.send(data);
</script>

```

不知道是否是我的代码问题，前来请教一下
Woker中的代码是直接复制粘贴的仓库中的woker.js中的代码

**Comment by tuhinpal** [comment]
That's because, you are using form data,

Just send some json object along with application/json content-type header


```
Method: POST
Content-Type: application/json
URL (Secured with Token): https://<your-app>.workers.dev/?key=<post-key>
URL (Not Secured): https://<your-app>.workers.dev/
BODY: Json Data (Not Parsed)
```

**Comment by tuhinpal** [comment]
Looks, like you didn't set the KV variable, So deploy it again. After that request it like this 👇

```
var data = JSON.stringify({
  "test": "ok"
});

var xhr = new XMLHttpRequest();
/ * xhr.withCredentials = true; */  // Brower doesn't allow wildcard (*) cross origin request while this is true

xhr.addEventListener("readystatechange", function() {
  if(this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", "https://kilovolt.tprojects.workers.dev/");
xhr.setRequestHeader("Content-Type", "application/json");

xhr.send(data);
```

**Comment by Drew233** [comment]
I'm so sorry that i still can't solve this problem,and I'm sure i set the KV variable because there is no problem in the brower in the cloudflare worker's page,but when i switch to my localhost this problem happened.

I tried your code and there is nothing different with mine.


![image](https://user-images.githubusercontent.com/47592224/113376081-837ea700-93a3-11eb-93e6-c0477b0f7b29.png)
![image](https://user-images.githubusercontent.com/47592224/113376132-998c6780-93a3-11eb-9f9c-8d81658f480b.png)


So sorry to trouble you.

**Comment by Drew233** [comment]
I don't know what happened, but it's working now, thank you very much!!!😁

**Comment by ZhaoTim** [comment]
@Drew233  我也遇到了同样的问题，能否麻烦问下如何解决呢？
